### ISSUE TITLE
Please move to Launch Library 2 or archive this repo

### ISSUE THREAD

**Issue by Nosudrum** [chadj/launch-library-slack-bot#1]
As stated on the Launch Library website since early 2020, support for the API provided from the launchlibrary.net URL has come to an end and the API will be closing down on December 31, 2020.
Starting November 1 there will be a launch asking to move to its successor : Launch Library 2.

If you intend to switch to the new API, you can find more details on The Space Devs website and Discord server:
https://thespacedevs.com/
https://discord.gg/p7ntkNA

Otherwise, please archive this repo or state clearly that it is no longer usable.

Thanks a lot,

The Space Devs team

**Comment by chadj** [comment]
Thanks for the heads up.  I just dropped an email to the author of the Ground Control slack bot and assuming he's updating his slack bot to the new API I'll just discontinue and archive this app while redirecting my users to Ground Control.

**Comment by Nosudrum** [comment]
We have not been in contact with this dev, so please let me know if he's switching to the new API or not when he answers :)

**Comment by chadj** [comment]
Here's the url to Ground Control if you want to reach out:

https://groundcontrolbot.space/

**Comment by Nosudrum** [comment]
His contact form seems to be broken, I'll reach out on twitter.

**Comment by chadj** [comment]
I used the email address provided here:

https://slack.com/apps/AA71CPL3D-ground-control

**Comment by Nosudrum** [comment]
Perfect thank you !

**Comment by chadj** [comment]
The new API is so close to the old one that I just went ahead and updated this slack bot.  It's now using the endpoints available at https://ll.thespacedevs.com/2.0.0/

**Comment by Nosudrum** [comment]
Awesome ! Make sure you're in the discord server if you want to be updated with the latest news and features :)
